# Generated by Django 3.2.6 on 2021-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='customers'),
        ),
    ]
