# Generated by Django 3.2.6 on 2021-11-06 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 10, 1, 20, 342166)),
        ),
    ]
