# Generated by Django 3.2.6 on 2021-09-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='additional',
            new_name='making',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='size',
        ),
        migrations.AddField(
            model_name='cake',
            name='cake_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cake'),
        ),
        migrations.AddField(
            model_name='cake',
            name='cost',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='cake',
            name='ingredients',
            field=models.TextField(default='none', max_length=550),
        ),
    ]
