# Generated by Django 3.2.6 on 2021-09-02 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cakespecs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakespecs',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
