# Generated by Django 3.2.6 on 2021-11-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakespecs', '0002_cakespecs_added_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cakespecs',
            new_name='Orders',
        ),
    ]
